layouts/partials/archived/extend-footer.html
layouts/partials/footer.html

I copied the "official" sentence the one can find the grant number easily

add  grant agreement number

---

content/news/2024-04-11-eosc-symposium-2024/index.md

- Updating news: Vote for the "Developing and Promoting Research Software Quality in EOSC" session at EOSC Symposium 2024

news: eosc symposium 2024

---

content/workpackages/01_Framework_European_Network/index.md

update to work package 1 description

changed WP1 description text

---

content/workpackages/06_Project_Management/index.md

I've changed the WP6 description for easer accessibility and readability to visitors.
Please check (again, sorry) if it's alright (still).
And sorry for the trouble last week.

WP6 description change

---

content/workpackages/03_Tools_and_Services/index.md

I've changed the WP§ description so that it is more accessible for readers/visitors.
Please have a look and let me know whether it is alright like that.

WP3 description new

---

content/_index.md

changed name "ENVRI-FAIR" to "ENVRI" and replaced old webpage link with the new one

changed ENVRI name and link

---

content/workpackages/02_Best_Practices/index.md

I've changed the work package description to the suggested text from #33 
Please have one more look.

WP2 Update with reviewed description

---

layouts/shortcodes/column-content.html
layouts/shortcodes/flex-content.html

Move from a simple string "Contains" to a regexp

More robust handling for column layouts

---

content/workpackages/05_Capacity_and_Recognition/index.md

I've changed the WP5 description such that it is more readable and accessible to visitors.
Please have a look at it and let me if it is alright like that.
Sorry for the trouble last week.

WP5 description change

---

assets/css/compiled/main.css
config/_default/hugo.yaml
config/_default/languages.en.yaml
config/_default/params.yaml
netlify.toml

Update some Hugo parameters and the current Blowfish version
N.B. currently Blowfish requires Hugo <= 0.135 - it's not yet compatible with 0.136

Maintainance updates

---

content/services/RSQkit.md

closes #52 
link added and it works.

RSQkit link added to EVERSE webpage

---

content/_index.md

As observed in today's WP1 meeting, these items should be presented right at the top of the webpage, so that they are the first things that people meet.
Care must be taken to keep this up to date!

Add highlight to newsletter and network

---

content/services/RSQkit.md

Don't use "here" links, try to improve search engine optimisation.

More prominent link to RSQkit

---

config/_default/menus.yaml

Suppress training menu

---

content/about/people/SanjeFenkart/index.md

added relevant information + applicable parameters

created the person page on Sanje

---

content/network/_index.md

Clearer layout for how to join the network
Closes #81

Improve layout and links for network page

---

content/privacy/index.md

Clarification on privacy policy cookies

---

content/_index.md
content/network/_index.md

Now that we did the event remove the alert banners

Remove launch alerts

---

config/_default/menus.yaml

changed social media handles from x/twitter to YouTube in footer
(named the branch wrong)

changed footer from twitter to Youtube

---

content/_index.md
content/network/webinars/index.md

added entries + links for webinars in may and June 2025 + changed banner alert to may webinar

Webinar may25 jun25

---

content/_index.md

banner for April 2025 newsletter

added banner for newsletter apr25

---

content/_index.md
content/network/webinars/index.md

Webinar date

---

config/_default/menus.yaml
config/_default/params.yaml
content/_index.md
content/about/objectives.md
content/about/scientific-advisory-board.md
content/contact.md
layouts/partials/article-pagination.html

1. I separated pagination for everse people and partners, now the navigation is not weird anymore (see `layouts/patials/article-pagination.html`)
2. I changed the alert/announcement in main page
3. I moved "Contact Everse" at the end of the Network dropdown menu

Pagination

---

content/network/webinars/index.md

added entry for the upcoming September webinar

entry for sept25 webinar
